### ISSUE TITLE
transit/read doesn't close InputStream

### ISSUE THREAD

**Issue by sashton** [cognitect/transit-clj#27]
I am trying to understand whether transit/read is supposed to close the InputStream. It currently doesn't, as demonstrated here:
```clj
(let [s "[\"~#list\",[0,1,2.0,true,false,\"five\",\"~:six\",\"~$seven\",\"~~eight\",null]]"
      close-count (atom 0)
      bais (proxy [ByteArrayInputStream] [(.getBytes s)]
             (close []
               (swap! close-count inc)
               (proxy-super close)))
      rdr (transit/reader bais :json {})
      result (transit/read rdr)]
  (println result)
  (println "InputStream closed" @close-count "times") ;prints out "0 times"!
  (.close bais)                                             ; show that close() really works
  (println "InputStream closed" @close-count "times")) ;now it prints out "1 times"
```
If I call `(transit/read rdr)` twice, it will close the InputStream the second time -- although there is nothing there to read since the InputStream is at the end position, so no data is returned.

**Comment by timewald** [comment]
Closing the input stream on read (or the output stream on write) would mean that only a single value could be read from or written to a given stream. With file streams, network streams, etc, you may want to read or write multiple values.

**Comment by sashton** [comment]
Thanks for clearing that up for me. That makes sense. I'll handle closing the InputStream myself after the call to `read`.
