### ISSUE TITLE
Transit reader fails on empty input

### ISSUE THREAD

**Issue by ikitommi** [cognitect/transit-clj#34]
Hi.

Should return `nil` instead?

``` clj
(require '[cognitect.transit :as transit])
(import [java.io ByteArrayInputStream])
(-> (byte-array 0) 
    (ByteArrayInputStream.) 
    (transit/reader :json) 
    (transit/read))
;; EOFException   com.cognitect.transit.impl.JsonParser.parse (JsonParser.java:44)
```

**Comment by dchelimsky** [comment]
Empty input is invalid input, hence the exception. If `read` returns a value, we assume that's a value that was sent over the wire, including `nil`. Same would be true for any sort of empty input marker. Make sense?

That said, I can't find anything in the docs about it, so I'll look into getting this documented. Leaving this open until I have an answer for you on that front.

**Comment by ikitommi** [comment]
Thanks for the quick reply. Added already a (non-optimal) safe-guard on our side.

Empty input is invalid also in JSON, but at least Cheshire doesn't fail with it:

```clj
(cheshire.core/parse-stream (java.io.InputStreamReader. (ByteArrayInputStream. (byte-array 0))))
;; nil
```

**Comment by dchelimsky** [comment]
I added the EOF to the doc and will cut a release later this week w/ the doc change.
