### ISSUE TITLE
transit/read throwing RuntimeException, not EOFException

### ISSUE THREAD

**Issue by danielcompton** [cognitect/transit-clj#35]
The docstring for transit/read says it throws an EOFException when the input is empty. However in [ReaderFactory](https://github.com/cognitect/transit-java/blob/v0.8.319/src/main/java/com/cognitect/transit/impl/ReaderFactory.java#L114), it catches all Throwables and rethrows them as RuntimeExceptions.

It seems like either the docstring for transit-clj read is wrong, or the implementation in transit-java shouldn't be catching all Throwables?

This is using transit-clojure 0.8.295 and transit-java 0.8.319

Here's a minimal test case to reproduce it:

```clj
(let [out (java.io.ByteArrayOutputStream. 4096)
      writer (transit/writer out :json)
      _ (transit/write writer {:a 1 :b 2 :c 3 :d 4})
      reader (transit/reader (java.io.ByteArrayInputStream. (.toByteArray out)) :json)]
  (transit/read reader)
  (try (transit/read reader)
       (catch java.io.EOFException e
         (println "Caught EOF Exception"))
       (catch RuntimeException e
         (println "Caught Runtime Exception"))))
```

**Comment by dchelimsky** [comment]
Just released 0.8.297 with the change to the docstring.

**Comment by dchelimsky** [comment]
And thanks for the report!

**Comment by danielcompton** [comment]
Should ReaderFactory catch all throwables or just exceptions? That seems a bit broad?

**Comment by dchelimsky** [comment]
What's your concern?

**Comment by danielcompton** [comment]
Throwable is much broader than the `IOException` that is expected to be thrown, and could mean that you catch Error's that shouldn't normally be caught (OOM), and would otherwise cause the program to crash.

http://stackoverflow.com/questions/2274102/difference-between-using-throwable-and-exception-in-a-try-catch
http://eclipsesource.com/blogs/2012/08/08/to-catch-or-not-to-catch-throwable/

I know that the API is pretty well set by now, but I think it might have made more sense to catch `IOException` and rethrow it, rather than catching all Throwables and rethrowing as RuntimeExceptions. If I want to catch the EOFException when parsing multiple items in a transit stream, I need to actually catch RuntimeException, then check it for EOF, and otherwise rethrow it.

**Comment by jarohen** [comment]
(sorry to dig up a relatively old issue)

I suspect my situation is pretty similar to @danielcompton - I have a stream of individual transit values that I want to keep reading until the stream closes, and I'm trying to figure out the cleanest way to determine that the end of the sequence has been reached. If I understand correctly, the proposed work-around is that we catch RuntimeException, then check the cause of the RuntimeException to see if it's an EOFException? I appreciate the docstring's been updated to say that c.t/read throws RuntimeException on EOF, but this is not the _only_ time it'll throw RuntimeException - any other Throwable, for example.

Taking the implementation of the Clojure reader as an example, could we provide an optional eof-value to c.t/read?
