### ISSUE TITLE
write-read roundtrip results in different value, when key of a map is a decimal

### ISSUE THREAD

**Issue by MrOerni** [cognitect/transit-clj#36]
My test generator found following, wrong behavior.

```clojure
(let [w (transit/writer :json) 
      r (transit/reader :json)]
      (transit/read r (transit/write w {0.5 0})))
==> {0 0}

(let [w (transit/writer :json)]
     (transit/write w {0.5 0.5}))
==> "[\"^ \",\"~i0.5\",0.5]"
```

Version: [com.cognitect/transit-cljs "0.8.239"]

**Comment by dchelimsky** [comment]
The code you provided doesn't run as/is (the constructors to writer and reader take output and input streams in addition to the format key), and here's what I get when I run this with code that runs:

```clojure
(for [t [:json :json-verbose]]
    (let [o (ByteArrayOutputStream. 2000)
          w (writer o t)]
      (write w {0.5 0})
      (.toString o)))
;; => ("[\"^ \",\"~d0.5\",0]" "{\"~d0.5\":0}")
(for [t [:json :json-verbose :msgpack]]
    (let [o (ByteArrayOutputStream. 2000)
          w (writer o t)]
      (write w {0.5 0})
      (let [i (ByteArrayInputStream. (.toByteArray o))
            r (reader i t)]
        (read r))))
;;=> ({0.5 0} {0.5 0} {0.5 0})
```

Can you provide a repro that I can run and watch behave the way you're saying? Maybe you're using some other stream implementations?

**Comment by MrOerni** [comment]
This issue is in the wrong repo.. My bad.

I use transit in clojurescript. Not clojure. Is there a way to move issues in Github?

**Comment by dchelimsky** [comment]
Not that I know of. I think you'll just have to open a new issue in transit-cljs.

**Comment by dchelimsky** [comment]
PS - I'd do it, but I think it's better if it comes from you so you can track it, etc.

**Comment by MrOerni** [comment]
https://github.com/cognitect/transit-cljs/issues/31
