### ISSUE TITLE
version 0.8.307 is broken?

### ISSUE THREAD

**Issue by ddellacosta** [cognitect/transit-clj#41]
Adding this to a vanilla lein project and running the most basic writer example yields:

```
broken-transit.core> (def out (ByteArrayOutputStream. 4096))
#'broken-transit.core/out
broken-transit.core> (def writer (transit/writer out :json))
#'broken-transit.core/writer
broken-transit.core> (transit/write writer "foo")
NullPointerException   cognitect.transit/writer/reify--5416 (transit.clj:160)
broken-transit.core>
```

[Example repo](https://github.com/ddellacosta/broken-transit). Details [here](https://github.com/ddellacosta/broken-transit/blob/master/src/broken_transit/core.clj).

UPDATE: in Slack, Alex Miller mentioned that the Java version may be relevant here, so adding that info just in case it helps:

```bash
$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
$
```

UPDATE 2: upgraded to JDK 10, still busted.

```bash
$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
$
```

**Comment by morgancmartin** [comment]
Can corroborate, 307 looks broken from here as well, same error as ddellacosta.

morgan@ubuntu-morgan:~$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

Dropping back down to 303 to continue working.

**Comment by empperi** [comment]
I can confirm this issue. Happens also on JDK 9.0.4.

**Comment by aiba** [comment]
Looks like 92e694b799cb41bbcaf530c0e61f80dff9c55c4f broke it by assuming `transform` was non-nil.  I am working around this by passing `identity` as the transform, e.g.:

```clj
(def writer (transit/writer out :json {:transform identity}))
```

**Comment by swannodette** [comment]
Sorry, this should be resolved in master and I'm cutting a new release now.

**Comment by ddellacosta** [comment]
Sorry @swannodette forgot to check back on this--looks like it's working fine for me after `0.8.309`, closing this out.
