### ISSUE TITLE
Add support for type ArrayMap

### ISSUE THREAD

**Issue by sirmspencer** [cognitect/transit-clj#48]
Im not sure if this is a CLJ or CLJS comment.  

When I send a larger array-map as transit, it loses order when being converted back in cljs.  It does look like the data continues to maintain order through the conversion to transit.

My array-map is 12 elements long (ie larger than than the 8 elements where the default map structure is already a array-map.  When my data was less than 8 elements, order was maintained.

**Comment by puredanger** [comment]
Transit maps are not ordered (and in general, adding this requirement might be difficult in other language implementations) so I do not think this is something that should be in transit-clj or transit-cljs.

**Comment by sirmspencer** [comment]
array-map -> transit does keep the order.  This could probably all be done in the cljs handler, with an optional parameter to set any map as an array-map.

**Comment by puredanger** [comment]
again, transit maps are not ordered and you shouldn't rely on that being preserved, even if it's a property of the current implementation

**Comment by puredanger** [comment]
Closing here, don't think there is anything to do. Could maybe discuss in transit-cljs.
