### ISSUE TITLE
Intended way to gracefully upgrade?

### ISSUE THREAD

**Issue by didibus** [cognitect/transit-clj#49]
The doc says:

> If storing Transit data durably, readers and writers are expected to use the same version of Transit and you are responsible for migrating/transforming/re-storing that data when and if the transit format changes.

Does Transit have any way to detect what version of Transit data it is dealing with? Or is it expected the application tracks separately which version a payload was encoded in, so that it chooses the correct version for decoding and possibly re-encoding in the new version?

**Comment by puredanger** [comment]
Transit data does not encode a version. I think the quoted passage answers this question - you are responsible.

That said, transit was released in 2014, has not changed in 6+ years, and no changes are planned. I imagine any breaking changes would be treated with great scrutiny.
