### ISSUE TITLE
Incorrect read from ByteArrayInputStream String.getBytes

### ISSUE THREAD

**Issue by johnbendi** [cognitect/transit-clj#52]
The code below demonstrates the problem

```
(let [body {:name ["John"]}
      out (ByteArrayOutputStream.)
      w (transit/writer out :msgpack)]
  (do (transit/write w body)
      (transit/read 
        (transit/reader (ByteArrayInputStream. (.getBytes (.toString out))) 
        :msgpack))))
;=> -17
```
But in the case of `:json` the code runs correctly. And also in the case `(ByteArrayInputStream. (.toByteArray out))` with `:msgpack` it runs correctly

**Comment by puredanger** [comment]
I think you misunderstand what ByteArrayOutputStream.toString() does - it prints bytes to a string using the platform encoding, which could be anything, and creates a string. Converting those to bytes (again, using some platform encoding) are the bytes of string representation, not the bytes of the original stream. So, you should not expect this to work.

https://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayOutputStream.html#toString()
