### ISSUE TITLE
Double/NaN is encoded as "NaN" in JSON

### ISSUE THREAD

**Issue by alexanderkiel** [cognitect/transit-clj#7]
Writing the value `Double/NaN` in JSON encoding emits just the string `NaN`. I would expect the string `~dNaN` or something similar. The spec says a JSON number should be emitted. As JSON doesn't support `NaN` in numbers, the explicit tagged string value of `~dNaN` would be an option.

This issue can be reproduced in a REPL:

```clojure
(import '[java.io ByteArrayOutputStream ByteArrayInputStream])
(require '[cognitect.transit :as transit])
(def out (ByteArrayOutputStream. 4096))
(def writer (transit/writer out :json))
(transit/write writer [Double/NaN])

(String. (.toByteArray out) "UTF-8")
```

The last expression evaluates to `"[\"NaN\"]"`. I enclosed `Double/NaN` in a vector to avoid more verbose [quoting](https://github.com/cognitect/transit-format#quoting).

It should be obvious that the reader can't read back the JSON string `NaN` as `Double/NaN`. So a simple round trip test with `Double/NaN` fails also.

The same is also true for `Double/POSITIVE_INFINITY` and `Double/NEGATIVE_INFINITY`.

**Comment by dchelimsky** [comment]
The "z" tag for special numbers was added to the spec: https://github.com/cognitect/transit-format#ground-and-extension-types for reference.
